package views;

import javafx.fxml.FXML;

import javafx.event.ActionEvent;
import javafx.scene.control.Alert;
import javafx.scene.control.Alert.AlertType;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.TilePane;
import javafx.scene.paint.Color;
import javafx.scene.paint.Paint;
import javafx.scene.shape.Rectangle;

public class AlbumsPageController {
	@FXML
	private TilePane TilePane;
	

	// Event Listener on MenuItem.onAction
	@FXML
	public void AddAlbum_Clicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on MenuItem.onAction
	@FXML
	public void EditAlbum_Clicked(ActionEvent event) {
		// TODO Autogenerated
	}
	
	@FXML
	public void Rectangle_Clicked(MouseEvent event) {
		
		Rectangle btn = (Rectangle) event.getSource();		
		Color c = (Color) btn.getFill();
		String hex = String.format( "#%02X%02X%02X",
		            (int)( c.getRed() * 255 ),
		            (int)( c.getGreen() * 255 ),
		            (int)( c.getBlue() * 255 ) );
		
		Alert alert = new Alert(AlertType.INFORMATION);
		alert.setTitle("Information Dialog");
		alert.setHeaderText("Look, an Information Dialog");
		alert.setContentText("Color: " + hex);
		alert.showAndWait();
	}
	
}
