package views;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import java.io.IOException;

import javafx.event.ActionEvent;

import javafx.scene.layout.TilePane;
import javafx.stage.Stage;
import javafx.scene.input.MouseEvent;

public class AlbumPhotosPageController {
	@FXML
	private Button Back_Button;
	@FXML
	private TilePane PhotosTilePane;

	// Event Listener on Button[#Back_Button].onAction
	@FXML
	public void BackButton_Clicked(ActionEvent event) throws IOException {
		 Stage stage; 
	     Parent root;     
	     
	     stage=(Stage) Back_Button.getScene().getWindow();
	     root = FXMLLoader.load(getClass().getResource("AlbumsPage.fxml"));

	     Scene scene = new Scene(root);
	     stage.setScene(scene);
	     stage.show();		
	}
	// Event Listener on Rectangle.onMouseClicked
	@FXML
	public void Rectangle_Clicked(MouseEvent event) {
		// TODO Autogenerated
	}
}
