package views;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.io.IOException;

import javafx.event.ActionEvent;

import javafx.scene.control.PasswordField;

public class LoginPageController {
	@FXML
	private TextField user_tb;
	@FXML
	private PasswordField pass_tb;
	@FXML
	private Button login_btn;
	@FXML
	private Button albumtest_btn;

	// Event Listener on Button[#login_btn].onAction
	@FXML
	public void Login_Clicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#albumtest_btn].onAction
	@FXML
	public void Test_Clicked(ActionEvent event) throws IOException {
		 Stage stage; 
	     Parent root;     
	     
	     stage=(Stage) albumtest_btn.getScene().getWindow();
	     root = FXMLLoader.load(getClass().getResource("AlbumsPage.fxml"));

	     Scene scene = new Scene(root);
	     stage.setScene(scene);
	     stage.show();
		
	}
}
